interface IBook {
    id: number,
    name: string,
    author: string,
    pages: number,
    publish: Date
}

export const books: IBook[] = [
    {
        id: 1,
        name: 'libro 1',
        author: 'author 1',
        pages: 170,
        publish: new Date(),
    },
    {
        id: 2,
        name: 'libro 1',
        author: 'author 1',
        pages: 80,
        publish: new Date(),
    },
    {
        id: 3,
        name: 'libro 1',
        author: 'author 1',
        pages: 69,
        publish: new Date(),
    },
    {
        id: 4,
        name: 'libro 1',
        author: 'author 1',
        pages: 170,
        publish: new Date(),
    },
    {
        id: 5,
        name: 'libro 1',
        author: 'author 1',
        pages: 80,
        publish: new Date(),
    },
    {
        id: 6,
        name: 'libro 1',
        author: 'author 1',
        pages: 69,
        publish: new Date(),
    },
    {
        id: 7,
        name: 'libro 1',
        author: 'author 1',
        pages: 170,
        publish: new Date(),
    },
    {
        id: 8,
        name: 'libro 1',
        author: 'author 1',
        pages: 80,
        publish: new Date(),
    },
    {
        id: 9,
        name: 'libro 1',
        author: 'author 1',
        pages: 69,
        publish: new Date(),
    },
    {
        id: 10,
        name: 'libro 1',
        author: 'author 1',
        pages: 170,
        publish: new Date(),
    },
    {
        id: 11,
        name: 'libro 1',
        author: 'author 1',
        pages: 80,
        publish: new Date(),
    },
    {
        id: 12,
        name: 'libro 1',
        author: 'author 1',
        pages: 69,
        publish: new Date(),
    },
    {
        id: 13,
        name: 'libro 1',
        author: 'author 1',
        pages: 170,
        publish: new Date(),
    },
    {
        id: 14,
        name: 'libro 1',
        author: 'author 1',
        pages: 80,
        publish: new Date(),
    },
    {
        id: 15,
        name: 'libro 1',
        author: 'author 1',
        pages: 69,
        publish: new Date(),
    },
    {
        id: 16,
        name: 'libro 1',
        author: 'author 1',
        pages: 170,
        publish: new Date(),
    },
    {
        id: 17,
        name: 'libro 1',
        author: 'author 1',
        pages: 80,
        publish: new Date(),
    },
    {
        id: 18,
        name: 'libro 1',
        author: 'author 1',
        pages: 69,
        publish: new Date(),
    },
    {
        id: 1,
        name: 'libro 1',
        author: 'author 1',
        pages: 170,
        publish: new Date(),
    },
    {
        id: 1,
        name: 'libro 1',
        author: 'author 1',
        pages: 80,
        publish: new Date(),
    },
    {
        id: 1,
        name: 'libro 1',
        author: 'author 1',
        pages: 69,
        publish: new Date(),
    },
];